### ISSUE TITLE
Is sponsus.com also part of Sponsus?

### ISSUE THREAD

**Issue by FunnyPunch** [AggressivelyMeows/SponsusFeaturesAndBugs#10]
When I come to Sponsus, I am already logged in. I typed sponsus.com and it took me to slightly different website, with the same look and even information to update my payment methods - which led to the sponsus.org sub-page. But at sponsus.com I was logged out and didn't want to log in - I refreshed sponsus.org and I was logged in there, but .com variant didn't see it - I didn't attempt to login there. If the answer to this is that Sponsus is using both and there are some problems with exchanging information - than delete this. If however that was attempted phishing, I suggest warning everybody.

**Comment by AggressivelyMeows** [comment]
Sponsus.com is owned by us however we are holding the domain so that someone else doesnt do what you described. Im sorry that it wasnt more obvious. Thank you for letting us know!

Also, i would highly recommend joining our Discord since the entire team is much more active there! https://sponsus.org/discord
